Http server tck (#372)
* test: HTTP Server TCK for tomcat, jetty and undertow

* apply new HTTP Server TCK

* ci: projectVersion 3.5.0-SNAPSHOT [ci skip]

* ci: githubCoreBranch 3.9.x [ci skip]

* bump up Micronaut Gradle Plugin to 3.6.7

* simplify build

* compatibility with Java 8

* build: update to MN 3.8.0

* build: update to MN Test 3.8.0

* test: update SSL tests

Backports fixes added in https://github.com/micronaut-projects/micronaut-servlet/pull/364

* source compatibility 1.8

* exclude RemoteAddressTest

test is failing with: org.opentest4j.AssertionFailedError: expected: <127.0.0.1> but was: <10.1.0.227>